name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Upload site
      uses: actions/upload-pages-artifact@v2
      with:
        path: './docs'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2